services:
  db-postgres:
    image: postgres
    container_name: db-postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env

node_app:
  container_name: node_app
  build: .
  ports:
    - 3000:3000
  depends_on:
    - db-postgres
  env_file:
    - .env