services:
  db-postgres:
    image: postgres
    container_name: db-postgres
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db-postgres
    env_file:
      - .env.test
