name: Pull request
on: [pull_request]
jobs:
  PullRequests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envKey_POSTGRES_USER="postgres"
          envKey_POSTGRES_PASSWORD="postgres"
          envKey_POSTGRES_DB="students"
          envKey_DATABASE_URL=postgresql://postgres:postgres@db-postgres:5432/students__tests
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node_app npm run test np 